kubeconfig_path: ~/.kube/config
kubevirt_namespace: proj-vms

vm_base_name: demo-vm
vm_count: 5        # zmienisz na 8 jak będziesz chciał dobudować
vm_cpu: "2"
vm_memory: "4Gi"
vm_disk_size: "20Gi"

vm_image_registry_url: "docker://quay.io/containerdisks/fedora:latest"
vm_ssh_key: "ssh-ed25519 AAAA...twoj_klucz..."

# Użyjesz tego TYLKO w kroku 2, jak już będziesz znał nazwę PVC z ISO
vm_iso_pvc_name: "tools-iso-pvc"
